import differential_geometric_methods_tensors_connections_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace differential_geometric_methods_tensors_connections_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end differential_geometric_methods_tensors_connections_theorem_canonical_lane_mathlib
end HautevilleHouse
